version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: pruebaconcepto
      POSTGRES_USER: pruebaconcepto
      POSTGRES_PASSWORD: pruebaconcepto
    volumes:
      - ./.deployment/docker/scripts/bbdd:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  jboss:
    build:
      context: .
      dockerfile: ./.deployment/docker/jboss/Dockerfile
    ports:
      - "8084:8084"
      - "9994:9994"
    environment:
      DB_URL: jdbc:postgresql://db:5432/pruebaconcepto
      DB_USER: pruebaconcepto
      DB_PASSWORD: pruebaconcepto
    depends_on:
      - db
